swagger: "2.0"
info:
  description: "API Piattaforma videogiochi"
  version: "0.0.1"
  title: "API Piattaforma videogiochi"
  
host: "tw.cs.unibo.it"
basePath: "/v1"
# Dobbiamo fare una sezione path con le varie operazioni
paths:
  # URL del menu
  /giochi/:
  #operazione di GET
   get:
    parameters:
      - name: category
        in: query
        type: string
        enum:
          - shooter
          - adventure
          - puzzle
          - sport
        required: true
    # # 1. ottenere l'elenco di tutti i giochi di una data categoria
    responses:
    # Due possibili risposte
      200:
        description: "OK"
        schema:
          type: array
          items: 
            $ref: "#/definitions/Gioco"
      400:
        description: "Generic error"
    
 
   post:
    parameters:
      - name: giochi
        in: body
        required: true
        schema:
          type: array
          items:
            type: string
            format: json
    # Descrizione get 
    responses:
    # Due possibili risposte
      200:
        description: "OK"
      400:
        description: "Generic error"
  
 # 2. modificare il numero minimo e massimo di giocatori in un gioco
  /giochi/{gameID}:
   post:
    parameters:
      - name: gameID
        in: path
        type: integer
        format: int64
        required: true
      - name: players
        in: body
        schema:
          $ref: "#/definitions/Gioco"
    # Descrizione get 
    responses:
    # Due possibili risposte
      200:
        description: "OK"
      400:
        description: "Generic error"
schemes:
- "http"

#sezione definitios dove definisco gli oggetti che utilizzo nella API
definitions:
  Category:
    type: string
    enum:
      - Shooter
      - adventure
      - puzzle
      - sport
  
  Players:
    type: integer
    format: int64
  
  Gioco:
    type: object
    # contiene l'elenco delle proprietà obbligatorie
    required:
      - id
      - name
      - category
      - players
    properties:
      id:
        type: integer
        format: int64
      name: 
        type: string
      category:
        $ref: "#/definitions/Category"
      players:
        $ref: "#/definitions/Players"
  
  
        
