swagger: "2.0"
info:
  description: Game API
  version: "0.0.1"
  title: "Game API"
  
host: "tw.cs.unibo.it"
basePath: "/v1"


paths:
  /giochi/:
    get:
      summary: Get games of a category
      parameters:
        - name: catID
          in: query
          description: id of the category
          required: true
          type: string
          enum:
            - Shooter
            - Adventure
            - Puzzle
            - Sport
      responses:
          200:
            description: "OK"
            schema:
              type: array
              items:
                $ref: "#/definitions/Gioco"
          400:
            description: "Error"
    post:
      summary: Add games
      parameters:
        - name: games
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/Gioco"
      responses:
        200:
          description: "OK"
        400:
          description: "Error"
                
          
            
  /giochi/{gameID}:
    post:
      summary: modify players
      parameters:
        - name: gameID
          in: path
          required: true
          type: integer
          format: int64
        - name: players
          in: body
          schema:
            $ref: "#/definitions/Gioco"
      responses:
        200:
          description: "OK"
        400:
          description: "Error"
        
      
schemes:
- "http"
  
  
definitions:
  Gioco:
    type: object
    required:
      - id
      - name
      - category
      - players
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      category:
          $ref: "#/definitions/Category"
      players:
          $ref: "#/definitions/Players"
  
  Category:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        enum:
          - Shooter
          - Adventure
          - Puzzle
          - Sport
  Players:
    type: integer
    format: int64